In [207]:
import pandas as pd
import numpy as np
import geopandas as gpd

# Load Contextual Data for the Community District 3 WebMap
## Step 1: Load Environmental Justice Area Data
Data come from NY.gov: https://data.ny.gov/Energy-Environment/Final-Disadvantaged-Communities-DAC-2023/2e6c-s6fp/about_data

In [208]:
# load cb 3 first to clip
gdf_sectors = gpd.read_file("data/acs_2023_mapbox.geojson")

# load ej data via the api
ej_area = gpd.read_file("https://data.ny.gov/resource/2e6c-s6fp.geojson?$limit=100000")
ej_area = ej_area[ej_area["dac_designation"] != "Not Designated as DAC"]
ej_area = ej_area.clip(gdf_sectors)
ej_area.to_crs(4326).to_file(
    "data/dac_area.geojson",
    driver="GeoJSON",
    layer_options={"ID_GENERATE": "YES"},
)

/opt/anaconda3/envs/cb3-census/lib/python3.13/site-packages/shapely/set_operations.py:131: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

## Step 2: Load parks polygons from the City of New York

In [209]:
df_parks = gpd.read_file(
    "https://data.cityofnewyork.us/resource/enfh-gkve.geojson?$limit=1000000"
)

In [210]:
df_parks[df_parks["communityboard"] == "103"].to_file("data/parks.geojson")

## Step 3: Load subsidized housing information from the NYU Furman Center

In [211]:
df_subsidized = pd.read_csv(
    "https://furmancenter.org/files/CoreData/FC_SHD_bbl_analysis_2024-08-29.csv"
)
df_subsidized.columns[30:]

/var/folders/_q/g5l2s5950hz1zr9syt43gzp80000gn/T/ipykernel_45359/3847649467.py:1: DtypeWarning: Columns (103,106,118) have mixed types. Specify dtype option on import or set low_memory=False.
  df_subsidized = pd.read_csv(

Index(['data_dof', 'data_hcrlihtc', 'data_hpd', 'data_hudcon', 'data_hudfin',
       'data_hudlihtc', 'data_ml', 'data_nycha', 'sub_fin', 'sub_prog',
       'sub_tax', 'sub_zone', 'prog_202_8', 'start_202_8', 'end_202_8',
       'prog_221d', 'start_221d', 'end_221d', 'prog_223', 'start_223',
       'end_223', 'prog_420c', 'start_420c', 'end_420c', 'prog_421a',
       'start_421a', 'end_421a', 'prog_421a_aff', 'start_421a_aff',
       'end_421a_aff', 'prog_8a', 'start_8a', 'end_8a', 'prog_hpd_oth',
       'start_hpd_oth', 'end_hpd_oth', 'prog_hud_fin_oth', 'start_hud_fin_oth',
       'end_hud_fin_oth', 'prog_hud_proj_oth', 'start_hud_proj_oth',
       'end_hud_proj_oth', 'prog_inclus_hous', 'start_inclus_hous',
       'end_inclus_hous', 'prog_j51', 'start_j51', 'end_j51', 'prog_lamp',
       'start_lamp', 'end_lamp', 'prog_lihtc4', 'start_lihtc4', 'end_lihtc4',
       'prog_lihtc9', 'start_lihtc9', 'end_lihtc9', 'prog_lmsa', 'start_lmsa',
       'end_lmsa', 'prog_mfp', 'start_mfp', 'end_mfp', 'prog_ml', 'start_ml',
       'end_ml', 'prog_nep', 'start_nep', 'end_nep', 'prog_nrp', 'start_nrp',
       'end_nrp', 'prog_nycha_mix', 'start_nycha_mix', 'end_nycha_mix',
       'prog_nycha_ph', 'start_nycha_ph', 'end_nycha_ph', 'prog_plp',
       'start_plp', 'end_plp', 'prog_prac_202', 'start_prac_202',
       'end_prac_202', 'prog_proj8', 'start_proj8', 'end_proj8', 'prog_rad',
       'start_rad', 'end_rad', 'prog_tpt', 'start_tpt', 'end_tpt',
       'prog_year15', 'start_year15', 'end_year15'],
      dtype='object')

### Connect subsidized housing data to the subsidized housing data

In [212]:
# load mappluto

# uncomment below to load the full PLUTO data
# pluto = gpd.read_file("data/nyc_mappluto_25v1_1_fgdb/MapPLUTO25v1_1.gdb")
# plutocb3 = pluto[pluto['CD']==103]
# plutocb3.to_file('data/cb3_pluto.geojson')

plutocb3 = gpd.read_file("data/cb3_pluto.geojson")

In [213]:
# merge on BBL
plutocb3_subhousing = plutocb3.merge(
    df_subsidized.rename(columns={"bbl": "BBL"}), on="BBL"
)

In [214]:
# identify NYCHA housing
nycha = plutocb3_subhousing[
    (plutocb3_subhousing["prog_nycha_mix"] == 1)
    | (plutocb3_subhousing["prog_nycha_ph"] == 1)
]
nycha["Address"] = nycha["Address"].str.strip()

/opt/anaconda3/envs/cb3-census/lib/python3.13/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [215]:
# add nycha development names
nycha_names = gpd.read_file(
    "https://data.cityofnewyork.us/resource/3ub5-4ph8.geojson?$limit=100000"
)
nycha_names = nycha_names[
    (nycha_names["community_district"] == "3") & (nycha_names["borough"] == "MANHATTAN")
]
# add names manually
nycha_manual = pd.read_excel("data/nycha_development_names.xlsx")
nycha_names = pd.concat(
    [nycha_names[["address", "development"]], nycha_manual], axis=0
).drop_duplicates()
nycha_names["address"] = nycha_names["address"].str.strip()
nycha_mgd = nycha.merge(
    nycha_names[["address", "development"]].drop_duplicates(),
    right_on="address",
    left_on="Address",
    how="left",
)

# save nycha data
nycha_mgd[["Address", "development", "geometry", "OwnerName"]].to_crs(4326).to_file(
    "data/nycha.geojson"
)

In [216]:
# identify section 8 housing
sec8 = plutocb3_subhousing[
    (plutocb3_subhousing["prog_proj8"] == 1) | (plutocb3_subhousing["prog_rad"] == 1)
]
sec8["name"] = np.select(
    [
        sec8["Address"].isin(
            ["606 EAST 13 STREET", "205 AVENUE C", "195 AVENUE B", "199 AVENUE B"]
        ),
        sec8["Address"].isin(["277 EAST 4 STREET", "279 EAST 4 STREET"]),
    ],
    ["CAMPOS PLAZA I", "LOWER EAST SIDE I"],
    "",
)
sec8.to_crs(4326).to_file("data/sec8.geojson")

/opt/anaconda3/envs/cb3-census/lib/python3.13/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [217]:
# identify mitchell-lama housing
ml = plutocb3_subhousing[(plutocb3_subhousing["prog_ml"] == 1)]

ml["name"] = np.select(
    [
        ml["Address"] == "100 CHERRY STREET",
        ml["Address"] == "645 WATER STREET",
        ml["Address"] == "605 WATER STREET",
        ml["Address"] == "604 WATER STREET",
        ml["Address"] == "35 MONTGOMERY STREET",
        ml["Address"] == "305 MADISON STREET",
        ml["Address"] == "40 1 AVENUE",
        ml["Address"] == "60 1 AVENUE",
        ml["Address"] == "66 1 AVENUE",
        ml["Address"] == "87 DELANCEY STREET",
        ml["Address"] == "162 AVENUE C",
        ml["Address"] == "620 EAST 13 STREET",
        ml["Address"] == "1 BOWERY",
    ],
    [
        "Knickerbocker Village",
        "Gouveneur Gardens",
        "Gouveneur Gardens",
        "Gouveneur Gardens",
        "Gouveneur Gardens",
        "Gouveneur Gardens",
        "Village View",
        "Village View",
        "Village View",
        "Masaryk Towers",
        "Village East",
        "Tanya Towers",
        "Confucius Plaza",
    ],
    "",
)
ml.to_crs(4326).to_file("data/ml.geojson")

/opt/anaconda3/envs/cb3-census/lib/python3.13/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

## Step 4: Load Crashes / Collision Data

In [218]:
# load crash data by year
gdf_crash_2023 = gpd.read_file(
    "https://data.cityofnewyork.us/resource/h9gi-nx95.geojson?$limit=10000000&$where=date_extract_y(crash_date)=2023"
)
gdf_crash_2024 = gpd.read_file(
    "https://data.cityofnewyork.us/resource/h9gi-nx95.geojson?$limit=10000000&$where=date_extract_y(crash_date)=2024"
)
gdf_crash_2025 = gpd.read_file(
    "https://data.cityofnewyork.us/resource/h9gi-nx95.geojson?$limit=10000000&$where=date_extract_y(crash_date)=2025"
)

Skipping field crash_time: unsupported OGR type: 10
Skipping field crash_time: unsupported OGR type: 10
Skipping field crash_time: unsupported OGR type: 10

In [219]:
# concatenate
gdf_crash = pd.concat([gdf_crash_2025, gdf_crash_2024, gdf_crash_2023])

In [220]:
# spatial join, add data columns
columns_to_drop = [
    x for x in gdf_sectors.columns if x in gdf_crash.columns and x != "geometry"
]
gdf_crash_cb3 = gdf_crash.sjoin(gdf_sectors.drop(columns_to_drop, axis=1), how="inner")
gdf_crash_cb3["crash_date"] = pd.to_datetime(gdf_crash_cb3["crash_date"])
gdf_crash_cb3["crash_month"] = gdf_crash_cb3["crash_date"].dt.month
gdf_crash_cb3["crash_year"] = gdf_crash_cb3["crash_date"].dt.year
gdf_crash_cb3.head()

,location_state,number_of_motorist_injured,zip_code,number_of_cyclist_killed,location_zip,contributing_factor_vehicle_3,latitude,on_street_name,collision_id,number_of_persons_killed,...,white_pct_pct_change,with_income_diff,with_income_pct_change,with_income_pct_diff,with_income_pct_pct_change,collision_count_x,collision_count_y,collision_count,crash_month,crash_year
31,,1,10002,0,,None,40.71376,GRAND ST,4783783,0,...,0.002916,266.0,0.018433,0.046660,0.056551,9.689655,9.689655,9.689655,1,2025
233,,0,None,0,,None,40.723835,FDR DRIVE,4783789,0,...,-0.597963,300.0,0.032690,0.011923,0.015545,7.241379,7.241379,7.241379,1,2025
329,,0,10013,0,,None,40.716812,CANAL ST,4783413,0,...,-0.011379,3247.0,0.592735,0.039790,0.047519,11.758621,11.758621,11.758621,1,2025
346,,0,10002,0,,None,40.716183,COLUMBIA ST,4783532,0,...,-0.106451,1358.0,0.151259,-0.003800,-0.004247,9.827586,9.827586,9.827586,1,2025
411,,0,10002,0,,None,40.719204,DELANCEY ST,4784191,0,...,0.012759,-607.0,-0.072564,-0.007445,-0.008736,18.827586,18.827586,18.827586,1,2025

In [221]:
collision_cols = [
    "number_of_motorist_injured",
    "number_of_cyclist_injured",
    "number_of_pedestrians_injured",
    "number_of_persons_injured",
    "number_of_motorist_killed",
    "number_of_cyclist_killed",
    "number_of_pedestrians_killed",
    "number_of_persons_killed",
]
gdf_crash_cb3[collision_cols] = gdf_crash_cb3[collision_cols].astype(int)

In [222]:
gdf_crash_cb3 = gdf_crash_cb3.to_crs(2263)
gdf_crash_cb3_buffer = gpd.GeoDataFrame(
    gdf_crash_cb3, geometry=gdf_crash_cb3.buffer(20)
).reset_index(drop=False)

In [223]:
intersects = gdf_crash_cb3_buffer.sjoin(
    gdf_crash_cb3_buffer, how="left", predicate="intersects"
)[
    [
        "index_left",
        "index_right",
        "latitude_left",
        "latitude_right",
        "longitude_left",
        "longitude_right",
        "geometry",
    ]
]
intersects_diss = intersects.dissolve("index_right", aggfunc="min")
intersects_diss = (
    intersects_diss.reset_index()
    .dissolve("index_left", aggfunc="min")[["geometry"]]
    .reset_index(drop=True)
)
gdf_crash_cb3_sjoin = gdf_crash_cb3.drop(
    columns=["index_right", "latitude", "longitude"]
).sjoin(intersects_diss)
gdf_crash_cb3_sjoin.geometry = gdf_crash_cb3_sjoin.centroid
gdf_crash_cb3_sjoin["latitude"] = gdf_crash_cb3_sjoin.geometry.y
gdf_crash_cb3_sjoin["longitude"] = gdf_crash_cb3_sjoin.geometry.x
gdf_crash_cb3_sjoin = gdf_crash_cb3_sjoin[
    ["latitude", "longitude", "crash_month", "crash_year", "collision_id"]
    + collision_cols
    + ["geometry"]
].drop_duplicates(keep="first")

/opt/anaconda3/envs/cb3-census/lib/python3.13/site-packages/shapely/set_operations.py:421: RuntimeWarning: invalid value encountered in unary_union
  return lib.unary_union(collections, **kwargs)
/opt/anaconda3/envs/cb3-census/lib/python3.13/site-packages/shapely/set_operations.py:421: RuntimeWarning: invalid value encountered in unary_union
  return lib.unary_union(collections, **kwargs)

In [224]:
# get count of crashes and totals for each intersection
df_crash_cb3_pts_counts = gdf_crash_cb3_sjoin.groupby(
    ["latitude", "longitude", "crash_month", "crash_year"], as_index=False
)[collision_cols].sum()
df_crash_cb3_pts = (
    gdf_crash_cb3_sjoin.value_counts(
        ["latitude", "longitude", "crash_month", "crash_year"]
    )
    .rename("collision_count")
    .reset_index()
    .merge(
        df_crash_cb3_pts_counts,
        on=["latitude", "longitude", "crash_month", "crash_year"],
    )
)
df_crash_cb3_pts.head()

,latitude,longitude,crash_month,crash_year,collision_count,number_of_motorist_injured,number_of_cyclist_injured,number_of_pedestrians_injured,number_of_persons_injured,number_of_motorist_killed,number_of_cyclist_killed,number_of_pedestrians_killed,number_of_persons_killed
0,201177.797385,991202.190880,6,2024,6,0,0,0,0,0,0,1,1
1,200763.234353,988194.609240,10,2023,6,7,0,0,7,0,0,0,0
2,201065.891738,987519.567678,1,2023,5,1,1,0,2,0,0,0,0
3,201177.797385,991202.190880,7,2023,5,0,0,0,1,0,0,0,0
4,200763.234353,988194.609240,1,2023,5,1,0,0,1,0,0,0,0

In [225]:
df_crash_cb3_pts["timescale"] = "monthly"
df_crash_cb3_pts = pd.concat(
    [
        df_crash_cb3_pts,
        df_crash_cb3_pts.groupby(
            ["crash_year", "latitude", "longitude"], as_index=False
        )[collision_cols + ["collision_count"]]
        .sum()
        .assign(timescale="yearly"),
        df_crash_cb3_pts.groupby(["latitude", "longitude"], as_index=False)[
            collision_cols + ["collision_count"]
        ]
        .sum()
        .assign(timescale="all"),
    ],
    axis=0,
)
df_crash_cb3_pts

,latitude,longitude,crash_month,crash_year,collision_count,number_of_motorist_injured,number_of_cyclist_injured,number_of_pedestrians_injured,number_of_persons_injured,number_of_motorist_killed,number_of_cyclist_killed,number_of_pedestrians_killed,number_of_persons_killed,timescale
0,201177.797385,991202.190880,6.0,2024.0,6,0,0,0,0,0,0,1,1,monthly
1,200763.234353,988194.609240,10.0,2023.0,6,7,0,0,7,0,0,0,0,monthly
2,201065.891738,987519.567678,1.0,2023.0,5,1,1,0,2,0,0,0,0,monthly
3,201177.797385,991202.190880,7.0,2023.0,5,0,0,0,1,0,0,0,0,monthly
4,200763.234353,988194.609240,1.0,2023.0,5,1,0,0,1,0,0,0,0,monthly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,206632.141880,987438.436168,NaN,NaN,1,0,1,1,2,0,0,0,0,all
1526,206639.015949,987055.704361,NaN,NaN,1,0,0,0,0,0,0,0,0,all
1527,206661.240211,987055.701748,NaN,NaN,3,0,0,0,0,0,0,0,0,all
1528,206703.156764,987207.015076,NaN,NaN,1,0,0,1,1,0,0,0,0,all
1529,206746.151076,987231.952277,NaN,NaN,2,0,1,0,1,0,0,0,0,all

In [241]:
gdf_crash_cb3_pts = gpd.GeoDataFrame(
    df_crash_cb3_pts,
    geometry=gpd.points_from_xy(df_crash_cb3_pts.longitude, df_crash_cb3_pts.latitude),
    crs="EPSG:2263",
).to_crs(4326)
gdf_crash_cb3_pts.head()
# save counts by intersections to a pts file
gdf_crash_cb3_pts.to_file("data/motor_vehicle_collisions.geojson")

In [242]:
gdf_crash_cb3_pts.shape

(6192, 15)

In [243]:
gdf_crash_cb3_pts[(gdf_crash_cb3_pts["timescale"] == "all")].sort_values("longitude")

,latitude,longitude,crash_month,crash_year,collision_count,number_of_motorist_injured,number_of_cyclist_injured,number_of_pedestrians_injured,number_of_persons_injured,number_of_motorist_killed,number_of_cyclist_killed,number_of_pedestrians_killed,number_of_persons_killed,timescale,geometry
234,199295.378707,983911.736639,NaN,NaN,1,0,0,0,0,0,0,0,0,all,POINT (-74.00122 40.7137)
33,198074.869005,983972.714484,NaN,NaN,1,0,0,0,0,0,0,0,0,all,POINT (-74.001 40.71035)
175,199052.733368,984003.218596,NaN,NaN,1,0,0,0,0,0,0,0,0,all,POINT (-74.00089 40.71303)
95,198567.079972,984008.759300,NaN,NaN,2,0,0,0,0,0,0,0,0,all,POINT (-74.00087 40.7117)
53,198222.058178,984061.431468,NaN,NaN,1,0,0,0,1,0,0,0,0,all,POINT (-74.00068 40.71075)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,203478.369020,991805.772332,NaN,NaN,6,1,0,0,1,0,0,0,0,all,POINT (-73.97274 40.72517)
1229,203834.009561,991971.964406,NaN,NaN,1,0,0,1,1,0,0,0,0,all,POINT (-73.97214 40.72615)
1230,203838.382431,991974.734731,NaN,NaN,1,1,0,0,1,0,0,0,0,all,POINT (-73.97213 40.72616)
1261,203983.393961,991997.970644,NaN,NaN,11,6,0,0,6,0,0,0,0,all,POINT (-73.97205 40.72656)
1247,203938.589724,992024.593472,NaN,NaN,2,3,0,0,3,0,0,0,0,all,POINT (-73.97195 40.72644)

In [244]:
# count number of collisions total
collision_count = (
    gdf_crash_cb3[["sectors", "crash_month", "crash_year"]]
    .value_counts()
    .rename("collision_count")
    .reset_index()
)
collision_count.head()

  sectors  crash_month  crash_year  collision_count
0       9            3        2023               29
1       9           10        2023               29
2       9           11        2023               28
3       9            5        2024               27
4       9            3        2024               26

In [245]:
# get totals by month, year, and sector
gdf_crash_cb3_total = (
    gdf_crash_cb3.groupby(["sectors", "crash_month", "crash_year"], as_index=False)[
        collision_cols
    ]
    .sum()
    .fillna(0)
    .merge(collision_count, on=["sectors", "crash_month", "crash_year"], how="outer")
)
collision_cols = collision_cols + ["collision_count"]
gdf_crash_cb3_total

,sectors,crash_month,crash_year,number_of_motorist_injured,number_of_cyclist_injured,number_of_pedestrians_injured,number_of_persons_injured,number_of_motorist_killed,number_of_cyclist_killed,number_of_pedestrians_killed,number_of_persons_killed,collision_count_x,collision_count_y
0,1,1,2023,1,3,0,4,0,0,0,0,178.344828,12
1,1,1,2024,2,2,0,4,0,0,0,0,163.482759,11
2,1,1,2025,1,1,2,4,0,0,0,0,163.482759,11
3,1,2,2023,2,3,0,5,0,0,0,0,89.172414,6
4,1,2,2024,9,0,0,9,0,0,0,0,148.620690,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,9,10,2024,5,3,6,14,0,0,0,0,414.206897,22
305,9,11,2023,8,4,3,15,0,0,0,0,527.172414,28
306,9,11,2024,2,1,4,7,0,0,0,0,225.931034,12
307,9,12,2023,3,4,1,8,0,0,0,0,395.379310,21
308,9,12,2024,6,1,1,8,0,0,0,0,357.724138,19

In [246]:
# ensure that months not included are set to 0
full_index = pd.MultiIndex.from_product(
    [
        gdf_crash_cb3_total["sectors"].unique(),
        gdf_crash_cb3_total["crash_month"].unique(),
        gdf_crash_cb3_total["crash_year"].unique(),
    ],
    names=["sectors", "crash_month", "crash_year"],
)

In [247]:
gdf_crash_cb3_complete = (
    gdf_crash_cb3_total.set_index(["sectors", "crash_month", "crash_year"])
    .reindex(full_index)
    .reset_index()
)
gdf_crash_cb3_complete = gdf_crash_cb3_complete[
    ~(
        (gdf_crash_cb3_complete["crash_month"] > 5)
        & (gdf_crash_cb3_complete["crash_year"] == 2025)
    )
]
# fill missing values with 0
gdf_crash_cb3_complete[collision_cols] = gdf_crash_cb3_complete[collision_cols].fillna(
    0
)
# compare the shapes
gdf_crash_cb3_complete.shape, gdf_crash_cb3_total.shape

KeyError: "['collision_count'] not in index"

In [248]:
gdf_crash_cb3_summary = gdf_crash_cb3_complete.groupby("sectors")[collision_cols].mean()
gdf_crash_cb3_summary

KeyError: "Columns not found: 'collision_count'"

In [234]:
# write this file to csv
gdf_crash_cb3_complete.to_csv("data/crash_summary.csv")

In [235]:
# gdf_sectors.drop(columns_to_drop, axis=1).merge(
#     gdf_crash_cb3_summary, on="sectors"
# ).to_file("data/acs_2023_mapbox.geojson")